# Initial Pipeline

trigger:
- master
- feature/*

stages:
- stage: Test
  jobs:
  - job: Python
    steps:
    - script: pip install .
      workingDirectory: ./tools/python/modules/ticker
      displayName: Local Module Installation
    - script: pip install -r ./requirements.txt
      workingDirectory: ./tools/python
      displayName: External Module Configuration
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        workingDirectory: './tools/python'
        scriptPath: './tools/python/run_tests.py'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: './tools/python/reports'
        mergeTestResults: true
