function(cxx_test name)
  add_executable(${name} "tests/${name}.cc")
  target_include_directories(${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/tests)
  foreach(lib ${ARGN})
    target_link_libraries(${name} PUBLIC ${lib})
  endforeach()
  add_test(NAME ${name} COMMAND "$<TARGET_FILE:${name}>")
endfunction()

function(cxx_sample name)
  add_executable(sample_${name} samples/${name}.cpp)
  foreach(lib ${ARGN})
    message(STATUS ${lib})
    target_link_libraries(sample_${name} PRIVATE ${lib})
  endforeach()
endfunction()
