# C++ Pipeline
#
# Pipeline configuration that defines the stages and steps required for
# building and testing pythong tools within the project
#
# Author: Elvis Payano

name: C++ Testing

# Triggers
# Run pipeline on all merges & updates to master
on:
  push:
    paths: ['**.cpp', '**.h', '**.cc', '**CMakeLists.txt']

jobs:
  build-tests:
    # Ensure Ubuntu runner
    runs-on: ubuntu-latest
    container: elvispayano/algo-trader-build:2.0
    steps:
    # Checkout source
    - uses: actions/checkout@v2
    
    # Run CMake
    - name: Build Linux
      run: |
        cmake -DBUILD_TESTS=ON .
        make -j $(nproc)
        ctest .
