# C++ Pipeline
#
# Pipeline configuration that defines the stages and steps required for
# building and testing pythong tools within the project
#
# Author: Elvis Payano

name: C++ Development

# Triggers
# Run pipeline on all merges to master
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
    - master
    paths:
    - '**.cpp'
    - '**.h'

jobs:
  Build:
    # Ensure Ubuntu runner
    runs-on: windows-latest

    # Run service containers
    services:
      postgres:
        image: postgres:9.6.18
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
        - "5431:5432"

    steps:
    # Checkout source
    - uses: actions/checkout@v2

    # Run CMake
    - name: Build Debug
      working-directory: ./trader
      run: |
        cmake .
        cmake --build .
        
    # Execute
    - name: Run Debug
      working-directory: ./trader/Debug
      run: |
        ./trader.exe
