# C++ Pipeline
#
# Pipeline configuration that defines the stages and steps required for
# building and testing pythong tools within the project
#
# Author: Elvis Payano

name: C++ Development

# Triggers
# Run pipeline on all merges & updates to master
on:
  pull_request:
    paths:
    - '**.cpp'
    - '**.h'
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build-debug:
    # Ensure Ubuntu runner
    runs-on: ubuntu-latest
    container: elvispayano/algo-trader-build:2.0
    steps:
    # Checkout source
    - uses: actions/checkout@v2
    
    # Run CMake
    - name: Build
      working-directory: ./trader
      run: |
        cmake .
        cmake --build . --config Debug

  build-release:
    # Ensure Ubuntu runner
    runs-on: ubuntu-latest
    container: elvispayano/algo-trader-build:2.0
    steps:
    # Checkout source
    - uses: actions/checkout@v2
    
    # Run CMake
    - name: Build
      working-directory: ./trader
      run: |
        cmake .
        cmake --build . --config Release
